name: flutter_reqres_test
description: Flutter test with REQRES API.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  api_bloc: ^2.0.1
  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.2
  dart_fusion_flutter:
    git:
      url: https://github.com/Nialixus/dart_fusion.git
      path: dart_fusion_flutter
      ref: v3.1.7
  dio: ^5.4.3+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.1.1
  http: ^1.2.1
  local_shared: ^1.0.5
  skeletonizer: ^1.1.2+1
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.5.3

flutter:
  uses-material-design: true
